// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: game/network/payload/payload.proto

package payload

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type ProtoGameState int32

const (
	ProtoGameState_PROTO_GAME_STATE_PAUSED         ProtoGameState = 0
	ProtoGameState_PROTO_GAME_STATE_ONGOING        ProtoGameState = 1
	ProtoGameState_PROTO_GAME_STATE_ROUND_FINISHED ProtoGameState = 2
	ProtoGameState_PROTO_GAME_STATE_GAME_FINISHED  ProtoGameState = 3
)

// Enum value maps for ProtoGameState.
var (
	ProtoGameState_name = map[int32]string{
		0: "PROTO_GAME_STATE_PAUSED",
		1: "PROTO_GAME_STATE_ONGOING",
		2: "PROTO_GAME_STATE_ROUND_FINISHED",
		3: "PROTO_GAME_STATE_GAME_FINISHED",
	}
	ProtoGameState_value = map[string]int32{
		"PROTO_GAME_STATE_PAUSED":         0,
		"PROTO_GAME_STATE_ONGOING":        1,
		"PROTO_GAME_STATE_ROUND_FINISHED": 2,
		"PROTO_GAME_STATE_GAME_FINISHED":  3,
	}
)

func (x ProtoGameState) Enum() *ProtoGameState {
	p := new(ProtoGameState)
	*p = x
	return p
}

func (x ProtoGameState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoGameState) Descriptor() protoreflect.EnumDescriptor {
	return file_game_network_payload_payload_proto_enumTypes[0].Descriptor()
}

func (ProtoGameState) Type() protoreflect.EnumType {
	return &file_game_network_payload_payload_proto_enumTypes[0]
}

func (x ProtoGameState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoGameState.Descriptor instead.
func (ProtoGameState) EnumDescriptor() ([]byte, []int) {
	return file_game_network_payload_payload_proto_rawDescGZIP(), []int{0}
}

type ProtoPerkType int32

const (
	ProtoPerkType_PROTO_PERK_TYPE_UNSPECIFIED ProtoPerkType = 0
	ProtoPerkType_PROTO_PERK_TYPE_WALK_WALL   ProtoPerkType = 1
	ProtoPerkType_PROTO_PERK_TYPE_DASH        ProtoPerkType = 2
)

// Enum value maps for ProtoPerkType.
var (
	ProtoPerkType_name = map[int32]string{
		0: "PROTO_PERK_TYPE_UNSPECIFIED",
		1: "PROTO_PERK_TYPE_WALK_WALL",
		2: "PROTO_PERK_TYPE_DASH",
	}
	ProtoPerkType_value = map[string]int32{
		"PROTO_PERK_TYPE_UNSPECIFIED": 0,
		"PROTO_PERK_TYPE_WALK_WALL":   1,
		"PROTO_PERK_TYPE_DASH":        2,
	}
)

func (x ProtoPerkType) Enum() *ProtoPerkType {
	p := new(ProtoPerkType)
	*p = x
	return p
}

func (x ProtoPerkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoPerkType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_network_payload_payload_proto_enumTypes[1].Descriptor()
}

func (ProtoPerkType) Type() protoreflect.EnumType {
	return &file_game_network_payload_payload_proto_enumTypes[1]
}

func (x ProtoPerkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoPerkType.Descriptor instead.
func (ProtoPerkType) EnumDescriptor() ([]byte, []int) {
	return file_game_network_payload_payload_proto_rawDescGZIP(), []int{1}
}

type ProtoDirection int32

const (
	ProtoDirection_PROTO_DIRECTION_EAST  ProtoDirection = 0
	ProtoDirection_PROTO_DIRECTION_NORTH ProtoDirection = 1
	ProtoDirection_PROTO_DIRECTION_SOUTH ProtoDirection = 2
	ProtoDirection_PROTO_DIRECTION_WEST  ProtoDirection = 3
)

// Enum value maps for ProtoDirection.
var (
	ProtoDirection_name = map[int32]string{
		0: "PROTO_DIRECTION_EAST",
		1: "PROTO_DIRECTION_NORTH",
		2: "PROTO_DIRECTION_SOUTH",
		3: "PROTO_DIRECTION_WEST",
	}
	ProtoDirection_value = map[string]int32{
		"PROTO_DIRECTION_EAST":  0,
		"PROTO_DIRECTION_NORTH": 1,
		"PROTO_DIRECTION_SOUTH": 2,
		"PROTO_DIRECTION_WEST":  3,
	}
)

func (x ProtoDirection) Enum() *ProtoDirection {
	p := new(ProtoDirection)
	*p = x
	return p
}

func (x ProtoDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_game_network_payload_payload_proto_enumTypes[2].Descriptor()
}

func (ProtoDirection) Type() protoreflect.EnumType {
	return &file_game_network_payload_payload_proto_enumTypes[2]
}

func (x ProtoDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoDirection.Descriptor instead.
func (ProtoDirection) EnumDescriptor() ([]byte, []int) {
	return file_game_network_payload_payload_proto_rawDescGZIP(), []int{2}
}

// Messages
type ProtoPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Y uint32 `protobuf:"varint,1,opt,name=y,proto3" json:"y,omitempty"`
	X uint32 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
}

func (x *ProtoPosition) Reset() {
	*x = ProtoPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_network_payload_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoPosition) ProtoMessage() {}

func (x *ProtoPosition) ProtoReflect() protoreflect.Message {
	mi := &file_game_network_payload_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoPosition.ProtoReflect.Descriptor instead.
func (*ProtoPosition) Descriptor() ([]byte, []int) {
	return file_game_network_payload_payload_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoPosition) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ProtoPosition) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

type ProtoPerk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   ProtoPerkType `protobuf:"varint,1,opt,name=type,proto3,enum=payload.ProtoPerkType" json:"type,omitempty"`
	Usages uint32        `protobuf:"varint,2,opt,name=usages,proto3" json:"usages,omitempty"`
}

func (x *ProtoPerk) Reset() {
	*x = ProtoPerk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_network_payload_payload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoPerk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoPerk) ProtoMessage() {}

func (x *ProtoPerk) ProtoReflect() protoreflect.Message {
	mi := &file_game_network_payload_payload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoPerk.ProtoReflect.Descriptor instead.
func (*ProtoPerk) Descriptor() ([]byte, []int) {
	return file_game_network_payload_payload_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoPerk) GetType() ProtoPerkType {
	if x != nil {
		return x.Type
	}
	return ProtoPerkType_PROTO_PERK_TYPE_UNSPECIFIED
}

func (x *ProtoPerk) GetUsages() uint32 {
	if x != nil {
		return x.Usages
	}
	return 0
}

type ProtoSnake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Perks     map[int32]*ProtoPerk `protobuf:"bytes,1,rep,name=perks,proto3" json:"perks,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // Perks map keyed by ProtoPerkType.
	Lives     uint32               `protobuf:"varint,2,opt,name=lives,proto3" json:"lives,omitempty"`
	Occupied  []*ProtoPosition     `protobuf:"bytes,3,rep,name=occupied,proto3" json:"occupied,omitempty"`
	Direction ProtoDirection       `protobuf:"varint,4,opt,name=direction,proto3,enum=payload.ProtoDirection" json:"direction,omitempty"`
	Points    uint32               `protobuf:"varint,5,opt,name=points,proto3" json:"points,omitempty"` // uint32 grows = 6;
}

func (x *ProtoSnake) Reset() {
	*x = ProtoSnake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_network_payload_payload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoSnake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSnake) ProtoMessage() {}

func (x *ProtoSnake) ProtoReflect() protoreflect.Message {
	mi := &file_game_network_payload_payload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSnake.ProtoReflect.Descriptor instead.
func (*ProtoSnake) Descriptor() ([]byte, []int) {
	return file_game_network_payload_payload_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoSnake) GetPerks() map[int32]*ProtoPerk {
	if x != nil {
		return x.Perks
	}
	return nil
}

func (x *ProtoSnake) GetLives() uint32 {
	if x != nil {
		return x.Lives
	}
	return 0
}

func (x *ProtoSnake) GetOccupied() []*ProtoPosition {
	if x != nil {
		return x.Occupied
	}
	return nil
}

func (x *ProtoSnake) GetDirection() ProtoDirection {
	if x != nil {
		return x.Direction
	}
	return ProtoDirection_PROTO_DIRECTION_EAST
}

func (x *ProtoSnake) GetPoints() uint32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type ProtoPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	World     string           `protobuf:"bytes,1,opt,name=world,proto3" json:"world,omitempty"`
	GameState ProtoGameState   `protobuf:"varint,2,opt,name=game_state,json=gameState,proto3,enum=payload.ProtoGameState" json:"game_state,omitempty"`
	Candies   []*ProtoPosition `protobuf:"bytes,3,rep,name=candies,proto3" json:"candies,omitempty"`
	Player    *ProtoSnake      `protobuf:"bytes,4,opt,name=player,proto3" json:"player,omitempty"`
	Opponents []*ProtoSnake    `protobuf:"bytes,5,rep,name=opponents,proto3" json:"opponents,omitempty"`
}

func (x *ProtoPayload) Reset() {
	*x = ProtoPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_network_payload_payload_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoPayload) ProtoMessage() {}

func (x *ProtoPayload) ProtoReflect() protoreflect.Message {
	mi := &file_game_network_payload_payload_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoPayload.ProtoReflect.Descriptor instead.
func (*ProtoPayload) Descriptor() ([]byte, []int) {
	return file_game_network_payload_payload_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoPayload) GetWorld() string {
	if x != nil {
		return x.World
	}
	return ""
}

func (x *ProtoPayload) GetGameState() ProtoGameState {
	if x != nil {
		return x.GameState
	}
	return ProtoGameState_PROTO_GAME_STATE_PAUSED
}

func (x *ProtoPayload) GetCandies() []*ProtoPosition {
	if x != nil {
		return x.Candies
	}
	return nil
}

func (x *ProtoPayload) GetPlayer() *ProtoSnake {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *ProtoPayload) GetOpponents() []*ProtoSnake {
	if x != nil {
		return x.Opponents
	}
	return nil
}

var File_game_network_payload_payload_proto protoreflect.FileDescriptor

var file_game_network_payload_payload_proto_rawDesc = []byte{
	0x0a, 0x22, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2b, 0x0a,
	0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x78, 0x22, 0x4f, 0x0a, 0x09, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x65, 0x72, 0x6b, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x65, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0xa9, 0x02, 0x0a, 0x0a,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x70, 0x65,
	0x72, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x50,
	0x65, 0x72, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x70, 0x65, 0x72, 0x6b, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x76, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x6c, 0x69, 0x76, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x08, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x69,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x12, 0x35, 0x0a, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x1a, 0x4c, 0x0a, 0x0a, 0x50, 0x65, 0x72,
	0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x65, 0x72, 0x6b, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xee, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x36,
	0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x09, 0x67, 0x61, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x52, 0x06, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x09, 0x6f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x52, 0x09, 0x6f,
	0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2a, 0x94, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x50,
	0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x50, 0x41, 0x55, 0x53, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x52, 0x4f, 0x54,
	0x4f, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x4e, 0x47,
	0x4f, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x23, 0x0a, 0x1f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f,
	0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x4f, 0x55, 0x4e, 0x44,
	0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x02, 0x12, 0x22, 0x0a, 0x1e, 0x50,
	0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x47, 0x41, 0x4d, 0x45, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x03, 0x2a,
	0x69, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x65, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1f, 0x0a, 0x1b, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x50, 0x45, 0x52, 0x4b, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x1d, 0x0a, 0x19, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x50, 0x45, 0x52, 0x4b, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x57, 0x41, 0x4c, 0x4b, 0x5f, 0x57, 0x41, 0x4c, 0x4c, 0x10, 0x01,
	0x12, 0x18, 0x0a, 0x14, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x50, 0x45, 0x52, 0x4b, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x44, 0x41, 0x53, 0x48, 0x10, 0x02, 0x2a, 0x7a, 0x0a, 0x0e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x14,
	0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x45, 0x41, 0x53, 0x54, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f,
	0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f, 0x52, 0x54, 0x48, 0x10,
	0x01, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x4f, 0x55, 0x54, 0x48, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14,
	0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x57, 0x45, 0x53, 0x54, 0x10, 0x03, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_network_payload_payload_proto_rawDescOnce sync.Once
	file_game_network_payload_payload_proto_rawDescData = file_game_network_payload_payload_proto_rawDesc
)

func file_game_network_payload_payload_proto_rawDescGZIP() []byte {
	file_game_network_payload_payload_proto_rawDescOnce.Do(func() {
		file_game_network_payload_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_network_payload_payload_proto_rawDescData)
	})
	return file_game_network_payload_payload_proto_rawDescData
}

var file_game_network_payload_payload_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_game_network_payload_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_game_network_payload_payload_proto_goTypes = []interface{}{
	(ProtoGameState)(0),   // 0: payload.ProtoGameState
	(ProtoPerkType)(0),    // 1: payload.ProtoPerkType
	(ProtoDirection)(0),   // 2: payload.ProtoDirection
	(*ProtoPosition)(nil), // 3: payload.ProtoPosition
	(*ProtoPerk)(nil),     // 4: payload.ProtoPerk
	(*ProtoSnake)(nil),    // 5: payload.ProtoSnake
	(*ProtoPayload)(nil),  // 6: payload.ProtoPayload
	nil,                   // 7: payload.ProtoSnake.PerksEntry
}
var file_game_network_payload_payload_proto_depIdxs = []int32{
	1, // 0: payload.ProtoPerk.type:type_name -> payload.ProtoPerkType
	7, // 1: payload.ProtoSnake.perks:type_name -> payload.ProtoSnake.PerksEntry
	3, // 2: payload.ProtoSnake.occupied:type_name -> payload.ProtoPosition
	2, // 3: payload.ProtoSnake.direction:type_name -> payload.ProtoDirection
	0, // 4: payload.ProtoPayload.game_state:type_name -> payload.ProtoGameState
	3, // 5: payload.ProtoPayload.candies:type_name -> payload.ProtoPosition
	5, // 6: payload.ProtoPayload.player:type_name -> payload.ProtoSnake
	5, // 7: payload.ProtoPayload.opponents:type_name -> payload.ProtoSnake
	4, // 8: payload.ProtoSnake.PerksEntry.value:type_name -> payload.ProtoPerk
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_game_network_payload_payload_proto_init() }
func file_game_network_payload_payload_proto_init() {
	if File_game_network_payload_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_network_payload_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_network_payload_payload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoPerk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_network_payload_payload_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoSnake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_network_payload_payload_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_network_payload_payload_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_network_payload_payload_proto_goTypes,
		DependencyIndexes: file_game_network_payload_payload_proto_depIdxs,
		EnumInfos:         file_game_network_payload_payload_proto_enumTypes,
		MessageInfos:      file_game_network_payload_payload_proto_msgTypes,
	}.Build()
	File_game_network_payload_payload_proto = out.File
	file_game_network_payload_payload_proto_rawDesc = nil
	file_game_network_payload_payload_proto_goTypes = nil
	file_game_network_payload_payload_proto_depIdxs = nil
}
